# Use IVIS to reduce the dimensionality of image data

In [ ]:
!pip install ivis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 648.0/648.0 KB 33.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.1-cp38-cp38-linux_x86_64.whl size=396888 sha256=b88e2aa24d2043fc2bc23041db23df697fab04505ddb5fe5005a1f59893c44a6
  Stored in directory: /root/.cache/pip/wheels/f9/93/19/30511c4a9ae6b4937455a134c34a39e13943e2c6f46fcd2ed2
Successfully built annoy


In [ ]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

1 Physical GPUs, 1 Logical GPUs


In [ ]:
# Ivis uses several stochastic processes.
# To make sure that results are consistent from one run to another,
# we fix the random seed

import os
os.environ["PYTHONHASHSEED"]="1234"

import random
import numpy as np

np.random.seed(1234)
random.seed(1234)
tf.random.set_seed(1234)

In [ ]:
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 KB 23.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.9/452.9 KB 28.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 40.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 23.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 25.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 101.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 73.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 17.1 MB/s eta 0:00:00
Mounted at /content/gdrive


In [ ]:
from fastbook import *
from fastai.vision.widgets import *

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/DL_images/temp_vs_trop/model_dev/'

In [ ]:
fns = get_image_files(path)
fns

In [ ]:
pilot_tt = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items=get_image_files,
    splitter=RandomSplitter(valid_pct=0.2, seed=42),
    get_y=parent_label,
    item_tfms=Resize(128))

In [ ]:
pilot_tt = pilot_tt.new(
    item_tfms=RandomResizedCrop(224, min_scale=0.5),
    batch_tfms=aug_transforms())


dls = pilot_tt.dataloaders(path)

In [ ]:
cd '/content/drive/MyDrive/DL_images/temp_vs_trop/model_dev/'

/content/drive/MyDrive/DL_images/temp_vs_trop/model_dev


## Load in the model that is trained to classify specimens into one of four groups

In [ ]:
learn_inf = load_learner('prunus_res50_temp_trop_v3_fp16_24epochs.pkl')


In [ ]:
learn_inf.model.cuda()

### These are the four groups:

In [ ]:
learn_inf.dls.vocab

['neotropical_racemose', 'paleotropical_racemose', 'temperate_diploid', 'temperate_racemose']

### Now define the hooks to get features from inner network layers

In [ ]:
class Hook():
    def __init__(self, m):
        self.hook = m.register_forward_hook(self.hook_func)
    def hook_func(self, m, i, o): self.stored = o.detach().clone()
    def __enter__(self, *args): return self
    def __exit__(self, *args): self.hook.remove()

In [ ]:
class HookBwd():
    def __init__(self, m):
        self.hook = m.register_backward_hook(self.hook_func)
    def hook_func(self, m, gi, go): self.stored = go[0].detach().clone()
    def __enter__(self, *args): return self
    def __exit__(self, *args): self.hook.remove()


In [ ]:
import pandas as pd

## The strategy is to load in images from specimens known to belong to each of the four categories

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose


In [ ]:
img_holder = os.listdir()

In [ ]:
len(img_holder)

100

In [ ]:
learn_inf.model

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose


In [ ]:
img_holder_temp_race = os.listdir()

In [ ]:
len(img_holder_temp_race)

100

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid


In [ ]:
img_holder_temp_dipl = os.listdir()

In [ ]:
len(img_holder_temp_dipl)

100

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose/

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose


In [ ]:
img_holder_trop_neo = os.listdir()

In [ ]:
len(img_holder_trop_neo)

100

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/paleotropical_racemose/

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/paleotropical_racemose


In [ ]:
img_holder_trop_pal = os.listdir()

In [ ]:
len(img_holder_trop_pal)

100

In [ ]:
img_holder_trop_pal

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve


### Get only representatives from the 400 total that are classified correctly with high accuracy

In [ ]:
filtered_df = pd.read_csv("test100_set.csv")

In [ ]:
paleo_race_imgs_df = filtered_df[filtered_df.classification == "paleotropical_racemose"]

In [ ]:
pr = paleo_race_imgs_df['image'].to_list()

In [ ]:
len(pr)

97

In [ ]:
neo_race_imgs_df = filtered_df[filtered_df.classification == "neotropical_racemose"]

In [ ]:
nr = neo_race_imgs_df['image'].to_list()

In [ ]:
len(nr)

65

In [ ]:
temp_race_imgs_df = filtered_df[filtered_df.classification == "temperate_racemose"]

In [ ]:
tr = temp_race_imgs_df['image'].to_list()

In [ ]:
len(tr)

77

In [ ]:
temp_dipl_imgs_df = filtered_df[filtered_df.classification == "temperate_diploid"]

In [ ]:
td = temp_dipl_imgs_df['image'].to_list()

In [ ]:
len(td)

96


# The loops to get vectors from model for those strongly classified



### Temperate racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = tr[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_temp_race = np.asarray(act_hold2)

In [ ]:
act_temp_race

array([[[ 0.9333843 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.32144293, -0.7372962 ]],

       [[ 0.95625395, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[ 0.58536696, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       ...,

       [[-0.6916634 , -0.5712142 ,  0.13919507, ..., -0.26591718, -0.29433134,  0.00665196]],

       [[-0.6725931 , -0.09186503, -0.14084442, ..., -0.7209007 ,  1.69959   , -0.7372962 ]],

       [[ 2.794887  , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]]], dtype=float32)

### Temperate diploid

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = td[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_temp_dipl = np.asarray(act_hold2)

In [ ]:
act_temp_dipl

array([[[-0.6916634 , -0.5712142 , -0.20737268, ..., -0.7209007 ,  2.1842215 , -0.476812  ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.3786743 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  2.3477604 ,  1.0534972 ]],

       ...,

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.74480754, -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  1.4509704 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.9980766 , -0.7372962 ]]], dtype=float32)

### Neotropical racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = nr[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_trop_neo = np.asarray(act_hold2)

In [ ]:
act_trop_neo

array([[[-0.49877098, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  1.0083547 ,  0.06104004]],

       [[-0.4815011 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.7355752 , -0.7372962 ]],

       ...,

       [[ 0.72521627, -0.5712142 , -0.10812803, ..., -0.7209007 , -0.65128195, -0.7372962 ]],

       [[ 0.9805852 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.61317545, -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]]], dtype=float32)

### Paleotropical racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/paleotropical_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/paleotropical_racemose


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = pr[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_trop_pal = np.asarray(act_hold2)

In [ ]:
act_trop_pal

array([[[ 0.15426646, -0.52265835, -0.5788494 , ..., -0.55679685, -0.6570689 , -0.7372962 ]],

       [[ 0.06092159,  1.1801544 , -0.5788494 , ..., -0.7209007 , -0.6525868 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.39502937, -0.7372962 ]],

       ...,

       [[ 0.7112668 , -0.01032911, -0.5788494 , ..., -0.6430118 , -0.6570689 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[ 1.6722367 , -0.01085315, -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]]], dtype=float32)

# All 100

### Temperate Racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_racemose


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = img_holder_temp_race[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_temp_race = np.asarray(act_hold2)

In [ ]:
act_temp_race

array([[[ 0.9333843 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.32144293, -0.7372962 ]],

       [[ 0.95625395, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[ 0.58536696, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       ...,

       [[-0.6725931 , -0.09186503, -0.14084442, ..., -0.7209007 ,  1.69959   , -0.7372962 ]],

       [[ 0.4219094 , -0.5712142 ,  0.6261389 , ..., -0.7209007 , -0.2628672 , -0.49679   ]],

       [[ 2.794887  , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]]], dtype=float32)

### Temperate diploid

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/temperate_diploid


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = img_holder_temp_dipl[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_temp_dipl = np.asarray(act_hold2)

In [ ]:
act_temp_dipl

array([[[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.74480754, -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  1.4509704 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 ,  0.9980766 , -0.7372962 ]],

       ...,

       [[-0.6916634 , -0.5712142 , -0.29715648, ..., -0.7209007 ,  2.9287143 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 ,  0.05380786, ..., -0.7209007 ,  0.83738476, -0.5024262 ]],

       [[-0.6916634 ,  0.9705017 ,  1.843571  , ..., -0.7209007 ,  2.5917215 ,  0.11333281]]], dtype=float32)

### Neotropical racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose

/content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/neotropical_racemose


In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = img_holder_trop_neo[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_trop_neo = np.asarray(act_hold2)

In [ ]:
act_trop_neo

array([[[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[-0.49877098, -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[ 0.49912098, -0.5712142 , -0.5788494 , ..., -0.3682443 , -0.6570689 , -0.7372962 ]],

       ...,

       [[ 0.13872603, -0.5712142 , -0.5788494 , ..., -0.46036986, -0.6570689 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]],

       [[-0.6916634 , -0.5712142 , -0.5788494 , ..., -0.7209007 , -0.6570689 , -0.7372962 ]]], dtype=float32)

### Paleotropical racemose

In [ ]:
cd /content/drive/MyDrive/DL_images/temp_vs_trop/test_reserve/paleotropical_racemose

In [ ]:
act_hold = []
act_hold2 = []
for counter in range(0,100):
  img = img_holder_trop_pal[counter];
  x, = first(dls.test_dl([img]));
  with Hook(learn_inf.model[1]) as hook:
      with torch.no_grad(): output = learn_inf.model.eval()(x.cuda())
      act = hook.stored
#  cls = 1
  with HookBwd(learn_inf.model[1][6]) as hookg:
      with Hook(learn_inf.model[1][6]) as hook:
          output = learn_inf.model.eval()(x.cuda())
          act = hook.stored
#  print("act: \n", act[0])
  act_hold.append(act)
  act_hold2.append(act.cpu().detach().numpy())


In [ ]:
act_trop_pal = np.asarray(act_hold2)

In [ ]:
act_trop_pal

# Here, we reshape the data and use IVIS to reduce the dimensionality of larger vectors into 2 dimensions


In [ ]:
act_temp_dipl.shape

(96, 1, 512)

In [ ]:
act_temp_race.shape

(77, 1, 512)

In [ ]:
act_trop_neo.shape

(65, 1, 512)

In [ ]:
act_trop_pal.shape

(97, 1, 512)

In [ ]:
temp_dipl = act_temp_dipl.reshape(96,512)

In [ ]:
temp_race = act_temp_race.reshape(77,512)

In [ ]:
trop_neo = act_trop_neo.reshape(65,512)

In [ ]:
trop_pal = act_trop_pal.reshape(97,512)

In [ ]:
temp_dipl_df = pd.DataFrame(temp_dipl)

In [ ]:
temp_race_df = pd.DataFrame(temp_race)

In [ ]:
trop_neo_df = pd.DataFrame(trop_neo)

In [ ]:
trop_pal_df = pd.DataFrame(trop_pal)

In [ ]:
master_df = pd.concat([temp_dipl_df, temp_race_df, trop_neo_df, trop_pal_df]).reset_index(drop=True)

In [ ]:
master_df

0         1         2         3         4         5         6    \
0   -0.691663 -0.571214 -0.207373  1.340048  1.954015 -0.675078 -0.582589   
1   -0.691663 -0.571214 -0.578849 -0.584143  1.183707 -0.675078 -0.582589   
2   -0.691663 -0.571214 -0.578849 -0.067589  0.344061 -0.675078  0.098911   
3   -0.691663 -0.571214 -0.578849 -0.584143  1.109027 -0.675078 -0.582589   
4   -0.691663 -0.241481 -0.314987  1.191335  2.384524 -0.675078 -0.238553   
..        ...       ...       ...       ...       ...       ...       ...   
330  0.705598 -0.571214 -0.578849  1.495849  0.849087  1.843696 -0.582589   
331 -0.691663 -0.571214 -0.578849  1.206077  0.107099  1.472418 -0.582589   
332  0.711267 -0.010329 -0.578849  1.034459  0.687654  1.060946 -0.582589   
333 -0.691663 -0.571214 -0.578849  1.501179 -0.381055  0.201407 -0.582589   
334  1.672237 -0.010853 -0.578849  1.016558  0.143698  0.649597 -0.582589   

          7         8         9         10        11        12        13   \
0    0.381872  1.286634  0.699695  1.374756  0.766746 -0.674187  0.326608   
1   -0.490935 -0.031176  0.269910 -0.532272 -0.492455 -0.532998 -0.017378   
2    0.161772  1.108900  2.255359 -0.532272  0.721348 -0.674187  0.104060   
3   -0.490935  1.044315 -0.680714 -0.532272 -0.492455 -0.674187 -0.182526   
4    0.713588  1.591030  1.634513 -0.532272  2.149673 -0.674187  0.527690   
..        ...       ...       ...       ...       ...       ...       ...   
330 -0.263441 -0.660776 -0.680714  1.308603 -0.351140 -0.197294 -0.683643   
331 -0.173167 -0.660776 -0.680714 -0.532272 -0.492455  1.484026 -0.683643   
332 -0.070295 -0.660776 -0.680714 -0.532272 -0.476901  0.454827 -0.683643   
333  1.664381 -0.660776 -0.680714 -0.532272 -0.492455  0.682174 -0.683643   
334  0.951115 -0.660776 -0.680714 -0.122362 -0.492455  0.176156 -0.683643   

          14        15        16        17        18        19        20   \
0   -0.709829 -0.608424 -0.531011  0.142737  1.099762 -0.683820  1.490188   
1   -0.673798 -0.608424 -0.531011 -0.635699  0.732989 -0.683820 -0.522113   
2   -0.709829 -0.608424 -0.531011 -0.635699  0.428122 -0.683820 -0.522113   
3   -0.650799 -0.608424  0.629241 -0.635699  0.369018 -0.683820 -0.522113   
4   -0.709829 -0.608424 -0.531011 -0.607800  0.687264 -0.683820 -0.522113   
..        ...       ...       ...       ...       ...       ...       ...   
330 -0.347691 -0.608424 -0.531011 -0.635699  0.659312  0.508348  0.412408   
331 -0.683566 -0.608424 -0.531011 -0.635699  1.280376  0.280766  0.188244   
332 -0.709829 -0.608424 -0.531011 -0.635699  1.745854  0.556419 -0.171916   
333 -0.709829 -0.608424 -0.531011 -0.635699  1.670036 -0.132874 -0.522113   
334 -0.709829 -0.250645 -0.531011 -0.375314  0.450152  1.572808  0.088021   

          21        22        23        24        25        26        27   \
0   -0.404739 -0.551825 -0.255449 -0.461177  0.351392 -0.608277 -0.711490   
1    0.190340 -0.044122  0.059602 -0.461177  0.847356 -0.608277 -0.711490   
2   -0.430720 -0.551825 -0.565545 -0.461177  1.618773 -0.608277 -0.711490   
3    1.274190  1.153525  0.138799 -0.461177 -0.030406 -0.608277 -0.711490   
4    0.057042 -0.551825 -0.426823 -0.390700  1.015165 -0.608277 -0.711490   
..        ...       ...       ...       ...       ...       ...       ...   
330 -0.430720 -0.551825 -0.343816 -0.461177 -0.596980 -0.608277  0.499218   
331 -0.267855  0.554257  0.372820 -0.461177  1.010100 -0.608277  0.319042   
332 -0.430720 -0.500010 -0.598117 -0.461177  0.608619 -0.608277 -0.146650   
333 -0.430720 -0.551825  0.784016  0.107913  0.133210 -0.608277 -0.711490   
334 -0.430720 -0.551825 -0.598117 -0.461177 -0.419151 -0.608277  1.693339   

          28        29        30        31        32        33        34   \
0    0.378350  1.208475  0.820407 -0.546186 -0.536626  0.011769 -0.725924   
1   -0.559392 -0.609136  1.074496 -0.546186 -0.536626 -0.550035 -0.725924   
2   -0.029873  1.169718  3.455611 -0.546186 -0.536626  0.443465 -0.725924   
3 

In [ ]:
from ivis import Ivis

In [ ]:
my_df = master_df.to_numpy()

In [ ]:
ivis_mod_strict = Ivis(model='maaten', n_epochs_without_progress=100, k =100, batch_size = 128)
ivis_mod_strict.fit(my_df)


In [ ]:
import matplotlib.pyplot as plt

from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')

In [ ]:
embeddings = ivis_mod_strict.transform(my_df)


3/3 [==============================] - 0s 5ms/step


In [ ]:
print(embeddings)

[[ 1.6157197e+00  3.8209958e+00]
 [ 3.3226821e+00  4.1602707e+00]
 [ 1.8879910e+00  4.3926363e+00]
 [ 3.4051902e+00  4.4075990e+00]
 [ 1.3390762e+00  4.0415630e+00]
 [-5.3071332e-01  2.8477182e+00]
 [ 3.1946099e-01  1.8536125e+00]
 [ 3.0216801e+00  4.0076313e+00]
 [ 2.9016879e+00  3.5615423e+00]
 [ 3.0934722e+00  4.2313380e+00]
 [ 1.5464381e+00  3.9137497e+00]
 [ 1.2102177e+00  3.5201797e+00]
 [ 3.1486535e+00  4.8090148e+00]
 [ 1.2678665e+00  3.6821330e+00]
 [ 2.8152635e+00  4.2329588e+00]
 [ 6.3067716e-01  3.6788132e+00]
 [ 2.9625177e+00  4.2523193e+00]
 [ 2.3159602e+00  3.5027945e+00]
 [ 2.4553908e-01  3.0484433e+00]
 [ 1.8434491e+00  4.0831170e+00]
 [ 1.6157109e+00  3.4505653e+00]
 [ 9.6052814e-01  3.9775534e+00]
 [-4.8103482e-01  2.1832571e+00]
 [-2.9834203e-02  2.4821277e+00]
 [ 1.0319201e+00  3.9111946e+00]
 [ 2.1540601e+00  3.6408820e+00]
 [ 2.8450415e-01  2.1698530e+00]
 [ 2.1070483e+00  4.5015473e+00]
 [ 2.1085351e+00  4.2169056e+00]
 [ 3.4138215e+00  3.8705599e+00]
 [-9.56299

In [ ]:
embed = pd.DataFrame(embeddings)

# These embeddings can be used to make a 2-dimensional representation of morphospace

In [ ]:
embed

0         1
0    1.615720  3.820996
1    3.322682  4.160271
2    1.887991  4.392636
3    3.405190  4.407599
4    1.339076  4.041563
..        ...       ...
330  2.963007 -1.473710
331  2.301740 -0.142881
332  2.816552 -0.905747
333  1.049766 -0.590789
334  3.190880 -1.441617

[335 rows x 2 columns]